### ISSUE TITLE
improvement for the mapVals

### ISSUE THREAD

**Issue by jt3k** [Mitranim/fpx#2]
I want to suggest an improvement for the mapVals function.
To be able to pass as the second argument a string
example:

```js
_.mapVals ([{a: 1, b: 2}, {a: 3, b: 4}], 'a') // => {0: 1, 1: 3}
```

**Comment by mitranim** [comment]
I looked into this a few days ago. The current thought process is that fpx should provide a key-getter function. Something like:

```js
f.mapVals({one: {value: 10}, two: {value: 20}}, f.getter('value'))
// {one: 10, two: 20}
```

Magic string→function conversion always struck me as dubious. The "right" thing is actually to define a getter function with a hardcoded key:

```js
f.mapVals({one: {value: 10}, two: {value: 20}}, getValue)
function getValue({value}) {return value}
```

In V8, the latter is significantly faster than the former, even in the context of the other costs of `mapVals`. I'm dubious about providing an interface that encourages the "wrong" thing.

On a related note, I'm preparing a massive fpx update, with better performance and tons of new functions, mostly lodash-compatible. Should be able to replace lodash, saving ≈40 KB minified. (Lodash is very space-inefficient.)

**Comment by jt3k** [comment]
okay, thnx )
